### ISSUE TITLE
No response when clicking "translate to ..."

### ISSUE THREAD

**Issue by nitech** [convergine/craft-content-buddy#1]
I've added an OpenAI API Key and chosen which fields should be available for ContentBuddy, but when I click "translate to en", nothing happens: 

![image](https://github.com/convergine/craft-content-buddy/assets/1279436/8c7b5a6a-683e-47c8-945e-a4227007ef65)

**Comment by convergine** [comment]
Hey @nitech
Thanks for submitting this one - we'll take a look and get back to you EOD Monday at the latest.

**Comment by convergine** [comment]
@nitech 
We've checked the issue on a new instance of multi-lingual CraftCMS and it works fine for us. 
1. Can you please open the developer console in your browser and see if there are any errors? If so, we'd appreciate if you could share either a screenshot or copy of the error.
2. Do any of the other prompts work (not the "translate to ...")?

**Comment by nitech** [comment]
Hi, thanks for responding. 

I tested some more, and see that the problem is only present on Craft Commerce Product Entries (as far as I can see): 

![no-response](https://github.com/convergine/craft-content-buddy/assets/1279436/3b2c3204-4c66-422b-a136-1e95b05d0c21)

It is working on normal entries.

**Comment by convergine** [comment]
This is very helpful, @nitech, thank you!
We'll take a look at Craft Commerce and if confirmed will address this in the next release.
