### ISSUE TITLE
Error when generating content: The section 'Foo' is not enabled for the site '1'

### ISSUE THREAD

**Issue by edbarbe** [convergine/craft-content-buddy#10]
The Site Id is hardcoded to 1 when creating an Entry [here](https://github.com/convergine/craft-content-buddy/blob/02152aa266006c41206b09e59c09e46bcda3c334/src/services/ChatGPT.php#L197)

This causes an error preventing the content generation when no Site exists with this id (1)
<img width="401" alt="CleanShot 2023-07-21 at 20 58 35@2x" src="https://github.com/convergine/craft-content-buddy/assets/4688587/5110bee1-f064-40b7-86cf-bfacd1b2ee7f">

It can be fixed using the Sites service `Craft::$app->sites->getCurrentSite()`.

**Comment by convergine** [comment]
Hey @edbarbe, 
Thank you for your contribution. Our team will include it in the next update.
