### ISSUE TITLE
Requests now hard-coded against /admin

### ISSUE THREAD

**Issue by nitech** [convergine/craft-content-buddy#12]
On my site I have overridden the default /admin URL for admin by using the `cpTrigger`-config attribute inside `config/general.php`. It seems the newest Content Buddy release is hard-coded to use /admin at times: 

![image](https://github.com/convergine/craft-content-buddy/assets/1279436/70385f28-9689-4edf-b605-f942e77b2f1b)

**Comment by convergine** [comment]
Thanks for reporting - we'll address it this week in release 1.0.6
