### ISSUE TITLE
Getting "rejected" from ChatGPT after newest version

### ISSUE THREAD

**Issue by nitech** [convergine/craft-content-buddy#14]
Up till newest CB, translation worked fine for larger texts. Now I am getting the following error message when translating for instance this text: 

![image](https://github.com/convergine/craft-content-buddy/assets/1279436/e399c264-2474-4983-8195-9d3874aaf417)

```
Vi deltar på INTERZUM og vil vise våre leverandørers produkter.

Hovedleverandører på denne messen er:

[Dürkopp Adler GmbH](https://www.amatec.no/kategori/leverandorer/durkopp-adler#category:22988@5:url) - Hall 10.1 Stand: A070/B071

ALFA Klebstoffe AG / SIMALFA® - Hall 10.1 Stand: D068/E069

[JUKI Central Europe Sp. z o.o. ](https://www.amatec.no/kategori/leverandorer/juki#category:19940@5:url)- Hall 10.1 Stand: B059

[Bullmer GmbH ](https://www.amatec.no/produkter/som-tekstil/tilskjaering/datastyrte-skjaeremaskiner#category:24950@5:url)- Hall 10.1 Stand: D048 - Vår nye leverandør av skjæremaskiner med opp til 5m bredde
```

**Comment by convergine** [comment]
Thanks @nitech 
All issues passed to our dev team and we are looking into it. We'll be releasing an update this week to address everything.

**Comment by convergine** [comment]
@nitech 
Can you please confirm which model are you using? Is it 4 or 3.5? 
Can you please try the different model, 4 vs 3.5 and vice-versa? 
This issue is coming from ChatGPT API rather than due to our code, it seems.

**Comment by nitech** [comment]
I was using the gpt-3.5-turbo-0301. Got the same error on gpt-3.5-turbo. 
However, when I tried doing the same request on my local ddev deployment it actually worked. 

The stranger thing is that when running the command on ddev, the request goes to: 

https://api.openai.com/v1/chat/completions
![image](https://github.com/convergine/craft-content-buddy/assets/1279436/7ae64d89-16b2-481a-a937-830fd451d7bb)

But when I run the translate command on my production instance, the request goes to: 

https://www.sitename.com/admin/actions/convergine-contentbuddy/prompt-processor/process
![image](https://github.com/convergine/craft-content-buddy/assets/1279436/16cc140b-a4e4-44e7-bf09-16542ba20003)

**Comment by nitech** [comment]
I notice that the specific error message that is returned comes from `Request.php:51`, and comes from what seems like a malformed submission to the OpenAPI endpoint. 

```php
	}elseif (strpos($message,'400 Bad Request')!=false){
		$message = Craft::t('convergine-contentbuddy', 'badRequestError');
```

As for why the request works on ddev and not on prod (it did work a week ago), I don't understand. I tried downgrading content buddy, but it didn't behave any different.

**Comment by nitech** [comment]
@convergine Any news on this and the other issues planned for next release?

**Comment by convergine** [comment]
Hi @nitech 
update will be released either later today or tomorrow. It's ready - just need to release it.
