### ISSUE TITLE
"Prompt not found" when translating to a different language on CB 1.0.6

### ISSUE THREAD

**Issue by nitech** [convergine/craft-content-buddy#15]
On Content Buddy 1.0.6, when clicking "Translate to en" (or any other language), I get the following: 

![image](https://github.com/convergine/craft-content-buddy/assets/1279436/7b17ab0e-4b63-4949-ac89-e67ca8b818e5)

![image](https://github.com/convergine/craft-content-buddy/assets/1279436/d65c5d50-8fcc-4d85-95d4-645a639738ba)

I tried adding a prompt for this manually, but it didn't work: 

![image](https://github.com/convergine/craft-content-buddy/assets/1279436/ddcd7316-7d1c-4fa2-bf24-693bf22c0901)

**Comment by nitech** [comment]
Any news on this?

**Comment by convergine** [comment]
Hi nitech, 
This will be resolved today/tomorrow - just need to release the update.

**Comment by nitech** [comment]
Sweet! Remember to update composer.json 😀

**Comment by convergine** [comment]
Hi @nitech 

The update was just released.
