### ISSUE TITLE
PHP error thrown when custom prompt template exceeds 255 characters

### ISSUE THREAD

**Issue by ajolsavsky** [convergine/craft-content-buddy#16]
See screenshots below. Error can be avoided when template Varchar length is increased. Possible to increase length to allow for more custom prompt maneuverability? Working solution shown in third screenshot.

![CleanShot 2023-09-14 at 11 57 26](https://github.com/convergine/craft-content-buddy/assets/100809744/f101c613-18de-4672-a0c9-4eaf2d54b30d)
![CleanShot 2023-09-14 at 11 57 01](https://github.com/convergine/craft-content-buddy/assets/100809744/b61e9173-fb32-4c76-80d7-fccea6e8da61)
![CleanShot 2023-09-14 at 11 20 58](https://github.com/convergine/craft-content-buddy/assets/100809744/04769500-77e8-4b97-9d57-b04821e93fee)

**Comment by convergine** [comment]
@ajolsavsky thanks for reporting this! We will address it in the next release, switching to "text" from "varchar"

**Comment by jacksoncool** [comment]
Is there an eta on this bug?

**Comment by convergine** [comment]
Hey @jacksoncool 
Should be addressed within next week
