### ISSUE TITLE
Slow results after triggering an action

### ISSUE THREAD

**Issue by jripmeester** [convergine/craft-content-buddy#18]
Hi there,

Multiple of our clients experience a slow interface while using content buddy.
When an action is triggered it can take a long time before a result is returned. We're talking about 10 seconds +.

Is this expected behaviour or are we missing something?

Thanks!

**Comment by convergine** [comment]
Hi @jripmeester 

Thank you for reporting this issue. We haven't seen such behavior yet. 

Could you please clarify a bit more - what specific actions are performed? Actions related to Content Buddy functionality? If that action is related to sending a request to the API (OpenAI or StabilityAI) then it is possible to have such delays as it relies on the API.
