### ISSUE TITLE
Multisite support

### ISSUE THREAD

**Issue by janhenckens** [convergine/craft-content-buddy#19]
When running the prompt on a section that is not enabled in the primary site, the buttons spins for a very long time without a clear error.

The logs then show an error that the section in question is not enabled for the current site (current site being the primary site since the request came from the CP). 

Changing the siteId [here](https://github.com/convergine/craft-content-buddy/blob/master/src/services/ContentGenerator.php#L199) fixes the issue, so a solution could be to add a dropdown to select the site alongside the section?

Happy to make a PR for this, just wanted to check in with you before I started.
Thanks
Jan

**Comment by janhenckens** [comment]
Reading through the issues is an extension of https://github.com/convergine/craft-content-buddy/issues/10.

**Comment by convergine** [comment]
Hi @janhenckens 
Thanks for this. We will include this fix in the update that will be released next week.
