### ISSUE TITLE
Dedicated button for translating to current site's language and reduce space on main button

### ISSUE THREAD

**Issue by nitech** [convergine/craft-content-buddy#2]
I have a few suggestions for the UI of Content Buddy, that you might consider: 

1. Make the Content Buddy dropdown smaller. It's a bit verbose now. 
2. Dedicated button for translating to current site's destination language. In the below screenshot, the base language is Norwegian and the currently selected language is Lithuanian. It would be nice to have a dedicated button called "LT" or something to translate the field to Lithuanian.

![image](https://github.com/convergine/craft-content-buddy/assets/1279436/d5e0fc5d-c13d-4430-929d-754ebfe0765e)

**Comment by convergine** [comment]
Hey @nitech 

Thank you for the suggestions! 
The button definitely needs to be smaller - we'll include this in the next release (this week)
We'll also take a look at the translation button option.
