### ISSUE TITLE
Migration for TranslateRecord never called

### ISSUE THREAD

**Issue by ddnetters** [convergine/craft-content-buddy#20]
The `TranslateController` calls `TranslateRecord` which gets used by the `/convergine-contentbuddy/site-translate` route but no migration exists for `TranslateRecord`. It leads to the route returning the following exception:
```
SQLSTATE[42S02]: Base table or view not found: 1146 Table 'db_name.content_buddy_translate' doesn't exist
The SQL being executed was: SELECT *
FROM `content_buddy_translate`
```

**Comment by convergine** [comment]
Thank you @ddnetters 
We'll look into this shortly.

**Comment by nitech** [comment]
Having same issue. 

![image](https://github.com/convergine/craft-content-buddy/assets/1279436/6c36ad67-1863-405a-b9de-2ff286caf0d8)

**Comment by convergine** [comment]
Thanks @nitech 
We're working on a few items for Content Buddy and will release a fix for this together with other improvements as soon as possible (hopefully within next week)

**Comment by ddnetters** [comment]
@convergine Could you share your release schedule and the allocated maintenance time for this plugin? That'd be valuable information for companies determining which plugin to move forward with.

**Comment by nitech** [comment]
Remember to run `./craft migrate/all` (or on ddev: `ddev craft migrate/all`) to reapply the missing db migration. This must be done on all environments, not just locally.
