### ISSUE TITLE
Migrations will be ignored for fresh install

### ISSUE THREAD

**Issue by sfsmfc** [convergine/craft-content-buddy#24]
If you have never installed the plugin and you use it in a fresh installation, the two migrations will not be called. Also a `migrate\all` doesn't show these migrations. If I move these migrations into my local folder, the system will see them.

A solution could be to add these changes also to Install.php script.

Tested with Craft 4.7.x.

Related to https://github.com/convergine/craft-content-buddy/issues/20.

**Comment by convergine** [comment]
@sfsmfc thank you for submitting this issue. 
It was resolved locally and will be released in next update (hopefully this week)

**Comment by sfsmfc** [comment]
Perfect, many thanks. Bug is fixed.
