### ISSUE TITLE
FR: Support for structures

### ISSUE THREAD

**Issue by lexisother** [convergine/craft-content-buddy#26]
Currently the plugin forces you to use channels for sections:
https://github.com/convergine/craft-content-buddy/blob/21e5193c286bde164bb301718f6ddaf791d3b965/src/services/Translate.php#L151

A couple of the sites I want to add Content Buddy to makes use of structures for pages. Could support for this be added?

**Comment by cbovers** [comment]
+1

**Comment by convergine** [comment]
Thank you for this. We'll look into it and see when can we add this.

**Comment by convergine** [comment]
Hey @cbovers, @lexisother 
This is now released under v1.1.4
