### ISSUE TITLE
Bug: Matrix blocks aren't created on existing entries

### ISSUE THREAD

**Issue by lexisother** [convergine/craft-content-buddy#27]
If the default site has a matrix field on an entry type with a couple blocks in it with fields that are translatable, Content Buddy doesn't create the matrix blocks if they don't exist on other sites. Instead, it errors out:

<img width="558" alt="image" src="https://github.com/convergine/craft-content-buddy/assets/54973868/3f8d67f7-a8e7-471c-b37a-27c2e07b79c3">

I assume this happens because Content Buddy tries to access the matrix field's blocks on the site you're trying to translate to when the blocks don't exist on said site. I expect Content Buddy to create the matrix blocks if they don't exist already.

The situation is as follows:

Source site:
<img width="366" alt="image" src="https://github.com/convergine/craft-content-buddy/assets/54973868/80d18581-1dd6-4b29-9a43-5f2ee4e33ffd">
Site I want to translate to:
<img width="386" alt="image" src="https://github.com/convergine/craft-content-buddy/assets/54973868/396bc0ef-022f-4e0c-9f38-a11847e5b691">

**Comment by convergine** [comment]
Thank you for reporting this bug - we'll look into it within this week/beginning of next.

**Comment by convergine** [comment]
Good day @lexisother, 

We released an update today to fix the error that pops up in this case. Please read the changelog about this specific issue: https://plugins.craftcms.com/convergine-contentbuddy/changelog?craft5#v1.1.4
