### ISSUE TITLE
Adjust the dedicated "translate to language"-button

### ISSUE THREAD

**Issue by nitech** [convergine/craft-content-buddy#3]
Thanks for listening to my suggestions in #2. I believe we've misunderstood each other slightly, so let me elaborate: 

1. I think it makes sense to have a dedicated button that translates the current field's content to the current site's language - not a dropdown that lists all languages of all sites. Think about it: Your plugin will be used a lot to simply translate the content from the base language to the current site's language.

(2. Also, the new button you added seems to list all languages on all sites. My multisite instance contains the following sites:)

![image](https://github.com/convergine/craft-content-buddy/assets/1279436/1574bfb8-c7e5-4efb-90f1-e837ef16ebc5)

The dedicated language dropdown has these options: 

![image](https://github.com/convergine/craft-content-buddy/assets/1279436/f5b6c1f8-7f32-40ee-a16f-b213bbfbc0a8)

--

So what I want is a dedicated button that translates the text to the _current site's language_. So if we are in the Amatec Norway English site, I want the button to say "en" and translate to English. If we are in the Amatec Lithuania Lithuanian site, I want the button to say "lt-LT" and translate to Lithuanian, etc. 

Get it? :-)

**Comment by convergine** [comment]
I see your point @nitech 
I think what we should do here is move the "current site language" translation option to the very top of that dropdown. That way we don't lose the option to translate to other languages, should the user need this for their scenario. So in your case, whenever you will be clicking on the dropdown - you will always see the "lt-LT" as the first option, if you are in Amatec Lithuania site. Thoughts?

**Comment by nitech** [comment]
That is a viable option. Plus of course making sure that the list doesn't repeat the language options.
