### ISSUE TITLE
Ckeditor craft 5 bugs

### ISSUE THREAD

**Issue by tibbis** [convergine/craft-content-buddy#34]
Hi!
In Ckeditor 5 craft cms 5 pro, the toolbar does not fit with the dropdown buttons:

<img width="1071" alt="Screenshot 2024-12-02 at 11 08 13" src="https://github.com/user-attachments/assets/871210d3-d696-4f2a-a205-4125a6d8087e">

Also the output is set to raw markdown and not previewed correctly in Ckeditor 5, can we solve that?:
<img width="1070" alt="Screenshot 2024-12-02 at 11 11 06" src="https://github.com/user-attachments/assets/b42075d1-a1e1-4bbc-b71f-f320c317ab65">

**Comment by convergine** [comment]
Hey @tibbis 
Thanks for reporting this. We'll look into it.

**Comment by convergine** [comment]
@tibbis 
#1 - confirmed and will be fixed in next release. 
#2 - we can't replicate it with OpenAI. Are you using xAI or OpenAI? xAI is known to remove formatting in reply and there's not much we can do about it at the moment.

**Comment by tibbis** [comment]
ah ok yeah its xAI with the content generator
