### ISSUE TITLE
Field's "remaining characters"-counter gets overlapped by Content Buddy's dropdown

### ISSUE THREAD

**Issue by nitech** [convergine/craft-content-buddy#4]
When a field has a max limit, the remaining characters are displayed in a label that is overlapped by the Content Buddy dropdown field: 

![image](https://github.com/convergine/craft-content-buddy/assets/1279436/c68b9d28-b3b6-4759-a25c-b5a8fb3b353b)

![image](https://github.com/convergine/craft-content-buddy/assets/1279436/46cd4ce7-70a4-4449-bb14-212315391567)

**Comment by nitech** [comment]
Still present: 

![image](https://github.com/convergine/craft-content-buddy/assets/1279436/e7627d2d-7ea2-496f-ae04-a57ab1e94fe5)

**Comment by convergine** [comment]
Works fine on our end. Cache issue maybe?
![image](https://github.com/convergine/craft-content-buddy/assets/7737586/fc4770a5-231a-43bc-bfd9-2b15fa801783)
