### ISSUE TITLE
FR: Ability to translate all content buddy enabled fields in one go

### ISSUE THREAD

**Issue by nitech** [convergine/craft-content-buddy#7]
We are translating a site to multiple languages. It would be very nice to have a button that allowed us to translate every Content Buddy enabled fields in one go (to a specific language)

**Comment by convergine** [comment]
Thanks for the feature request Simon! We'll look into this.

**Comment by convergine** [comment]
Hey @nitech 
Just wanted to update you on this FR. We are working with the team right now on how to better implement this feature. Hoping to deliver this in near future, within August.

**Comment by karensg** [comment]
Amazing, looking forward to try this. If you have a beta version, let us know.

**Comment by convergine** [comment]
Hey @karensg 
Thanks for your interest!
We're 90% done with this feature and I hope we'll release it in 1.0.7 at either the end of next week or the week after.

**Comment by convergine** [comment]
@karensg @nitech 
We have just released an update with the new functionality that allows to translate whole website.

**Comment by nitech** [comment]
Hi, I cannot see that this feature has actually been implemented. I see you've added the "Site translation" menu item in CP, but that's not what I am asking for in this FR. I am asking for the ability to translate all Content Buddy enabled fields in one go for an entry (or product). Right now I have to click "translate to xyz" on each field. I would like just one button for this: 

![image](https://github.com/convergine/craft-content-buddy/assets/1279436/9c739dd8-dee4-4f36-af90-ed6345c96bf4)

**Comment by convergine** [comment]
Hi @nitech 
Thank you for the screenshot. Yes, Site translation doesn't work the way you described on screenshot.
I'm reopening this task and we'll try to work on this after 1.1.0 (which focuses mainly on CraftCMS 5 support). If not in 1.1.0 - it will be released in the next version right after it.

**Comment by convergine** [comment]
Hi @nitech 
We have just released the update with craftcms 5 support and now will work on this feature.

**Comment by convergine** [comment]
Hey @acmhmedia 
This feature was developed recently, we just need to release it. Next week if not today/tomorrow.

**Comment by convergine** [comment]
@acmhmedia @nitech @karensg 
This feature is now available in the latest release.
