### ISSUE TITLE
Should close dropdown when clicking next dropdown

### ISSUE THREAD

**Issue by nitech** [convergine/craft-content-buddy#8]
See screenshot:

![image](https://github.com/convergine/craft-content-buddy/assets/1279436/1fa5a6c5-dcb3-4d08-99f5-895a617ee983)

**Comment by convergine** [comment]
Hey @nitech 
Our team checked it out and it doesn't look like we'll be able to do anything about it. These are CraftCMS dropdowns and we don't have much control over their behavior.

**Comment by nitech** [comment]
Ok, thanks
