### ISSUE TITLE
Matrix block support

### ISSUE THREAD

**Issue by jripmeester** [convergine/craft-content-buddy#9]
Question. How do you activate Content Buddy on text/redactor fields in Matrix blocks?

**Comment by convergine** [comment]
Hi @jripmeester 
Apologies for the delay. Our team will look into this end of the week/beginning of next one.

**Comment by convergine** [comment]
@jripmeester Good news! We've added this enhancement and will be releasing the update tomorrow/Wednesday.

**Comment by jripmeester** [comment]
@convergine That's great news! Will be wathcing out for the update.
Thanks!
